//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.pandaos.smartconfig;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.FrameLayout;
import android.widget.TextView;
import com.pandaos.smartconfig.R.id;
import com.pandaos.smartconfig.R.layout;
import com.pandaos.smartconfig.utils.SharedPreferencesInterface_;

public final class QRScannerActivity_
    extends QRScannerActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_qrscanner);
    }

    private void init_(Bundle savedInstanceState) {
        prefs = new SharedPreferencesInterface_(this);
    }

    private void afterSetContentView_() {
        activity_qrscanner_next = ((TextView) findViewById(id.activity_qrscanner_next));
        camera_preview = ((FrameLayout) findViewById(id.camera_preview));
        {
            View view = findViewById(id.activity_qrscanner_next);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        QRScannerActivity_.this.activity_qrscanner_next();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static QRScannerActivity_.IntentBuilder_ intent(Context context) {
        return new QRScannerActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, QRScannerActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public QRScannerActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
