//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.pandaos.smartconfig;

import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.pandaos.smartconfig.R.layout;
import com.pandaos.smartconfig.utils.MDnsHelper_;
import com.pandaos.smartconfig.utils.SharedPreferencesInterface_;

public final class SmartConfigFragment_
    extends SmartConfigFragment
{

    private View contentView_;
    private Handler handler_ = new Handler();

    private void init_(Bundle savedInstanceState) {
        prefs = new SharedPreferencesInterface_(getActivity());
        mDnsHelper = MDnsHelper_.getInstance_(getActivity());
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        smartconfig_network_name_field = ((EditText) findViewById(com.pandaos.smartconfig.R.id.smartconfig_network_name_field));
        smartconfig_key_layout = ((RelativeLayout) findViewById(com.pandaos.smartconfig.R.id.smartconfig_key_layout));
        smartconfig_network_pass_field = ((EditText) findViewById(com.pandaos.smartconfig.R.id.smartconfig_network_pass_field));
        smartconfig_device_name_layout = ((RelativeLayout) findViewById(com.pandaos.smartconfig.R.id.smartconfig_device_name_layout));
        tab_smartconfig_view = ((RelativeLayout) findViewById(com.pandaos.smartconfig.R.id.tab_smartconfig_view));
        smartconfig_key_field = ((EditText) findViewById(com.pandaos.smartconfig.R.id.smartconfig_key_field));
        smartconfig_device_name_field = ((EditText) findViewById(com.pandaos.smartconfig.R.id.smartconfig_device_name_field));
        smartconfig_progressbar = ((ProgressBar) findViewById(com.pandaos.smartconfig.R.id.smartconfig_progressbar));
        smartconfig_key_button = ((ImageView) findViewById(com.pandaos.smartconfig.R.id.smartconfig_key_button));
        smartconfig_network_pass_eye = ((ImageView) findViewById(com.pandaos.smartconfig.R.id.smartconfig_network_pass_eye));
        smartconfig_device_name_explanation_layout = ((RelativeLayout) findViewById(com.pandaos.smartconfig.R.id.smartconfig_device_name_explanation_layout));
        title_smartconfig = ((TextView) findViewById(com.pandaos.smartconfig.R.id.title_smartconfig));
        smartconfig_start = ((TextView) findViewById(com.pandaos.smartconfig.R.id.smartconfig_start));
        {
            View view = findViewById(com.pandaos.smartconfig.R.id.smartconfig_key_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SmartConfigFragment_.this.smartconfig_key_button();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.pandaos.smartconfig.R.id.tab_smartconfig_view);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SmartConfigFragment_.this.tab_smartconfig_view();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.pandaos.smartconfig.R.id.smartconfig_network_pass_eye);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SmartConfigFragment_.this.smartconfig_network_pass_eye();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(com.pandaos.smartconfig.R.id.smartconfig_start);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SmartConfigFragment_.this.smartconfig_start();
                    }

                }
                );
            }
        }
        ((MDnsHelper_) mDnsHelper).afterSetContentView_();
        afterViews();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.tab_smartconfig_view, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static SmartConfigFragment_.FragmentBuilder_ builder() {
        return new SmartConfigFragment_.FragmentBuilder_();
    }

    @Override
    public void notifyFoundNewDevice() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.notifyFoundNewDevice();
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void updateProgressBar(final int runTime) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.updateProgressBar(runTime);
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void hideTabs() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.hideTabs();
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void resetProgressBar() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.resetProgressBar();
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void notifyNotFoundNewDevice() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.notifyNotFoundNewDevice();
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void runProgressBar() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.runProgressBar();
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void lookForNewDevice() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.lookForNewDevice();
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void pauseMDNS() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SmartConfigFragment_.super.pauseMDNS();
                } catch (RuntimeException e) {
                    Log.e("SmartConfigFragment_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        SmartConfigFragment_.super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  0 :
                SmartConfigFragment_.this.onResult(resultCode, data);
                break;
        }
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public SmartConfigFragment build() {
            SmartConfigFragment_ fragment_ = new SmartConfigFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
