//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.pandaos.smartconfig.utils;

import android.app.Activity;
import android.content.Context;
import android.widget.ImageView;
import android.widget.TextView;
import com.pandaos.smartconfig.R.id;
import com.pandaos.smartconfig.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class DeviceItemView_
    extends DeviceItemView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public DeviceItemView_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        devices_list_item_image = ((ImageView) findViewById(id.devices_list_item_image));
        devices_list_item_name = ((TextView) findViewById(id.devices_list_item_name));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.list_devices_item, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static DeviceItemView build(Context context) {
        DeviceItemView_ instance = new DeviceItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

}
