//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.pandaos.smartconfig.utils;

import android.content.Context;
import android.content.SharedPreferences;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.BooleanPrefField;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.IntPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.IntPrefField;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class SharedPreferencesInterface_
    extends SharedPreferencesHelper
{


    public SharedPreferencesInterface_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_SharedPreferencesInterface"), 0));
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_ edit() {
        return new SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_(getSharedPreferences());
    }

    public StringPrefField devicesArray() {
        return stringField("devicesArray", "[]");
    }

    public BooleanPrefField isScanning() {
        return booleanField("isScanning", false);
    }

    public BooleanPrefField isSmartConfigActive() {
        return booleanField("isSmartConfigActive", false);
    }

    public BooleanPrefField openInDevicesList() {
        return booleanField("openInDevicesList", false);
    }

    public StringPrefField recentDevicesArray() {
        return stringField("recentDevicesArray", "[]");
    }

    public BooleanPrefField showDeviceName() {
        return booleanField("showDeviceName", true);
    }

    public BooleanPrefField showSmartConfigPass() {
        return booleanField("showSmartConfigPass", false);
    }

    public BooleanPrefField skipScanDisplay() {
        return booleanField("skipScanDisplay", false);
    }

    public IntPrefField startTab() {
        return intField("startTab", 0);
    }

    public final static class SharedPreferencesInterfaceEditor_
        extends EditorHelper<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_>
    {


        SharedPreferencesInterfaceEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> devicesArray() {
            return stringField("devicesArray");
        }

        public BooleanPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> isScanning() {
            return booleanField("isScanning");
        }

        public BooleanPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> isSmartConfigActive() {
            return booleanField("isSmartConfigActive");
        }

        public BooleanPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> openInDevicesList() {
            return booleanField("openInDevicesList");
        }

        public StringPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> recentDevicesArray() {
            return stringField("recentDevicesArray");
        }

        public BooleanPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> showDeviceName() {
            return booleanField("showDeviceName");
        }

        public BooleanPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> showSmartConfigPass() {
            return booleanField("showSmartConfigPass");
        }

        public BooleanPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> skipScanDisplay() {
            return booleanField("skipScanDisplay");
        }

        public IntPrefEditorField<SharedPreferencesInterface_.SharedPreferencesInterfaceEditor_> startTab() {
            return intField("startTab");
        }

    }

}
